spring.application.name=Pair Wise Live Backend Service

spring.datasource.url=${PAIRWISE_DB_URL}
spring.datasource.username=${PAIRWISE_DB_USERNAME}
spring.datasource.password=${PAIRWISE_DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${PAIRWISE_JPA_SHOW_SQL}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect